CLASS ltcl_note_dao DEFINITION FINAL FOR TESTING
  DURATION SHORT
  RISK LEVEL HARMLESS.

  PRIVATE SECTION.
    METHODS:
      conversion_ok FOR TESTING.
ENDCLASS.


CLASS ltcl_note_dao IMPLEMENTATION.

  METHOD conversion_ok.
  ENDMETHOD.

ENDCLASS.
